import { Inter } from 'next/font/google'
import {Header} from "@/app/components/Header";


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Градиент - продажа геодезического оборудования',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body>
        <Header/>
        {children}
      </body>
    </html>
  )
}
